### ISSUE TITLE
[suggestion] Change dual-licensing

### ISSUE THREAD

**Issue by hotchpotch** [guoyunhe/flexbin#2]
I like this scss library, convenient and easy to use. thanks!

However this library lisense is GPLv3, therefore I can't use this library. For example, [Bootstrap is MIT lisense](https://getbootstrap.com/docs/4.2/about/license/), so I can't compile Bootstrap css with flexbin.scss.

If you change license MIT and GPLv3 dual-licensing, then I can compile with other MIT,BSD libraries 😃.

**Comment by guoyunhe** [comment]
That is **NOT** how licenses work. You can compile it along with libraries of any licenses. The only restriction is to your final output. Are you building a website? Or another library?

If you are building a website, you shouldn't worry about it because you are not distribute the software to end users.

If you are building another library, then it needs to be GPL compatible.

**Comment by hotchpotch** [comment]
I see, the final output css is no problem. I understood.
Thank you!
